# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  frontend:
    build:
      context: .
    environment:
      - NODE_ENV=production
      - IMAGES_URL=http://127.0.0.1:8000/images
      - PLACEHOLDER_IMAGE=http://127.0.0.1:8000/images/placeholder.jpg
      - BACKEND_URL=http://127.0.0.1:8000
    ports:
      - 4200:8080


